#!/bin/bash
#eval "java -jar jenkins-cli.jar -s http://52.88.112.178:8080/ build 'Direwolf'"

curBranch=`git rev-parse --abbrev-ref HEAD`
usr=`whoami`
time=`date +%s`

branchName="$curBranch"_build

git checkout -b $branchName
git push origin $branchName

if [ $curBranch == "dev" ]
then
	java -jar jenkins-cli.jar -s http://52.89.132.135:8080/ build 'dev'
elif [ $curBranch == "release" ]
then
	java -jar jenkins-cli.jar -s http://52.89.132.135:8080/ build 'release'	
fi

#curl -X POST http://52.88.112.178:8080/job/devops/branch/$branchName/build?delay=0sec

git checkout $curBranch
git push origin :$branchName
git branch -D $branchName

# TOKEN GATE
git diff HEAD~1 | grep -i + >check_diff
# Regex to find the AWS Access Key ID
AWS=`grep '[0-9,A-Z]\{20\}$' check_diff|wc -l`
# Regex to find the Digital Ocean Token
DO=`grep '[0-9,a-f,A-F]\{64\}$' check_diff|wc -l`
# Regex to find the AWS Secret
SECRET=`grep '[0-9,A-Z,a-z]\{40\}$' check_diff|wc -l`
# ssh private key
SSHKEYS=`grep -e 'ssh-rsa [0-9,A-Z,a-z,+,/]\{372\} [a-z]*@[a-z]*' check_diff|wc -l`
if [ $AWS -eq 0 ]
then
   if [ $DO -eq 0 ]
   then
      if [ $SECRET -eq 0 ]
      then
         echo "All Set, Lets commit"
      else
         git reset HEAD~1
         echo "SSH Secret key"
      fi
   else
      echo "DO present"
      git reset HEAD~1
   fi
else
   echo "AWS present"
   git reset HEAD~1
fi

